version: "3.9"

# docker-compose up -d
# docker-compose down
# docker rm $(docker ps -a -q) && docker volume prune -f

# psql -h localhost -U postgres -d urls-service
# \dt
# SELECT * FROM urls;

services:

  urls-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urls-service_app_container
    environment:
      - POSTGRES_CONN=postgres://postgres:postgres@urls-service-db:5432/urls-service
    restart: unless-stopped
    depends_on:
      urls-service-db:
        condition: service_healthy
    ports:
      - "8080:8080"

  urls-service-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urls-service
      - POSTGRES_HOST_AUTH_METHOD=md5
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d urls-service" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    expose:
      - "5432"